export const PACKAGE_LIST_PATHS = [
  '/azerbaijan-tours',
  '/turkiye-tours',
  '/uzbekistan-tours',
  '/kazakhstan-tours',
  '/kyrgyzstan-tours',
  '/georgia-tours',
  '/poland-tours',
  '/russia-tours',
  '/ukraine-tours',
]

export const TOUR_DETAIL_PATHS = [
  '/golf-azerbaijan',
  '/shahdag',
  '/absheron-tour',
  '/baku-night-tour',
  '/jeep-safari-tour-1',
  '/jeep-safari-tour-2',
  '/jeep-safari-on-the-gobustan-reserve',
  '/jeep-safari-on-the-gobustan-reserve-extreme',
  '/museum-gobustan-mud-volcano',
  '/old-city-excursion',
  '/azerbaijani-cuisine',
  '/gabala-tour',
  '/khinalig-tour',
  '/sheki-tour',
  '/quba-tour',
  '/lahic-tour',
  '/almaty-tour',
  '/bishkek-tour',
  '/turkiye-tour',
  '/uzbekistan-tour',
  '/georgia-tour',
  '/russia-tour',
  '/krakow-tour',
  '/kyiv-tour',
]
