const tour = (path, title, description, keywords, priority = '0.75') => ({
  path,
  title: `${title} | Zakher Travel`,
  description,
  keywords,
  changefreq: 'monthly',
  priority,
  schema: 'touristTrip',
  tripName: title,
})

export const NOINDEX_PATHS = new Set(['/confirm', '/reservation'])

export const SEO_PAGES = [
  {
    path: '/',
    title: 'Zakher Travel | Azerbaijan Tour Operator & Incoming Travel Agency',
    description:
      'Zakher Travel is a licensed Azerbaijan tour operator offering Baku city tours, Caucasus tour packages, MICE, visa support, hotel booking and DMC services since 2016.',
    keywords:
      'Azerbaijan tour operator, Baku travel agency, incoming tours Azerbaijan, Caucasus tours, DMC Baku, visa support Azerbaijan, tour packages',
    changefreq: 'weekly',
    priority: '1.0',
    schema: 'home',
  },
  {
    path: '/about-us',
    title: 'About Zakher Travel | Licensed Tour Operator in Azerbaijan',
    description:
      'Learn about Zakher Travel, a full-service incoming tour operator in Baku serving GCC and international travelers across Azerbaijan, Turkey, Georgia and Central Asia.',
    keywords: 'about Zakher Travel, Azerbaijan tour company, incoming tour operator Baku',
    changefreq: 'monthly',
    priority: '0.9',
  },
  {
    path: '/who-we-are',
    title: 'Who We Are | Zakher Travel Team & Mission',
    description:
      'Meet Zakher Travel: expert destination managers, licensed guides and travel professionals delivering tailored tours and corporate travel across the Caucasus.',
    keywords: 'Zakher Travel team, travel professionals Azerbaijan, DMC experts',
    changefreq: 'monthly',
    priority: '0.8',
  },
  {
    path: '/ourbranches',
    title: 'Our Branches | Zakher Travel Worldwide Offices',
    description:
      'Zakher Travel branches and partner offices across Azerbaijan, Turkey, Georgia, Kazakhstan, Poland, UAE and more. Local expertise for every destination.',
    keywords: 'Zakher Travel branches, travel agency offices, Baku travel company',
    changefreq: 'monthly',
    priority: '0.8',
  },
  {
    path: '/ourservices',
    title: 'Travel Services | Tours, MICE, Medical & Real Estate | Zakher Travel',
    description:
      'Tourism services, MICE events, medical travel, real estate assistance, transfers, visa support, hotel booking and VIP travel solutions by Zakher Travel.',
    keywords: 'travel services Azerbaijan, MICE Baku, medical tourism, visa support, DMC services',
    changefreq: 'monthly',
    priority: '0.9',
  },
  {
    path: '/tour-packages',
    title: 'Tour Packages | Azerbaijan & International | Zakher Travel',
    description:
      'Explore curated tour packages across Azerbaijan, Turkey, Georgia, Central Asia and Europe. Private tours, group travel, adventure and cultural experiences.',
    keywords: 'Azerbaijan tour packages, international tours, group travel, private tours Baku',
    changefreq: 'weekly',
    priority: '0.95',
  },
  {
    path: '/azerbaijan-tours',
    title: 'Azerbaijan Tours | Baku, Gabala, Sheki & More | Zakher Travel',
    description:
      'Discover the best Azerbaijan tours: Baku old city, Gobustan, Gabala, Sheki, Quba, Shahdag and custom itineraries with professional guides and transport.',
    keywords: 'Azerbaijan tours, Baku tours, Gabala tour, Sheki tour, Caucasus travel',
    changefreq: 'weekly',
    priority: '0.95',
  },
  {
    path: '/contact-us',
    title: 'Contact Zakher Travel | Baku Tour Operator',
    description:
      'Contact Zakher Travel in Baku for tour quotes, MICE requests, visa support and travel planning. Phone +994 12 310 09 32, info@zakher.travel',
    keywords: 'contact Zakher Travel, Baku travel agency contact, tour quote Azerbaijan',
    changefreq: 'monthly',
    priority: '0.85',
  },
  {
    path: '/social-media',
    title: 'Zakher Travel on Social Media',
    description: 'Follow Zakher Travel on Facebook, Instagram and LinkedIn for tour updates, travel inspiration and special offers.',
    keywords: 'Zakher Travel social media, Azerbaijan travel Instagram',
    changefreq: 'monthly',
    priority: '0.5',
  },
  {
    path: '/about-events',
    title: 'Events & MICE | Zakher Travel Azerbaijan',
    description:
      'Corporate events, incentives, conferences and exhibitions in Azerbaijan and abroad. End-to-end MICE planning by Zakher Travel.',
    keywords: 'MICE Azerbaijan, corporate events Baku, conferences Azerbaijan',
    changefreq: 'monthly',
    priority: '0.7',
  },
  {
    path: '/about-branch',
    title: 'Branch Information | Zakher Travel',
    description: 'Detailed information about Zakher Travel branch offices, local teams and destination coverage.',
    keywords: 'Zakher Travel branch, local travel office',
    changefreq: 'monthly',
    priority: '0.6',
  },
  {
    path: '/reservation',
    title: 'Tour Reservation | Zakher Travel',
    description: 'Submit your tour reservation request to Zakher Travel.',
    keywords: 'tour reservation Azerbaijan',
    changefreq: 'yearly',
    priority: '0.3',
    noindex: true,
  },
  {
    path: '/confirm',
    title: 'Reservation Confirmation | Zakher Travel',
    description: 'Your reservation request has been received by Zakher Travel.',
    keywords: 'reservation confirmation',
    changefreq: 'yearly',
    priority: '0.2',
    noindex: true,
  },
  {
    path: '/azerbaijan',
    title: 'Travel to Azerbaijan | Destination Guide | Zakher Travel',
    description:
      'Plan your trip to Azerbaijan with Zakher Travel. Baku, ancient history, Caspian Sea, mountains, cuisine and four-season tourism in the Caucasus.',
    keywords: 'travel to Azerbaijan, Azerbaijan destination, visit Baku, Caucasus tourism',
    changefreq: 'monthly',
    priority: '0.85',
  },
  {
    path: '/turkiye',
    title: 'Travel to Turkey | Tour Packages | Zakher Travel',
    description: 'Turkey tour packages and DMC services by Zakher Travel. Istanbul, Cappadocia, Antalya and custom Turkish itineraries.',
    keywords: 'Turkey tours, Turkiye travel, Istanbul tour packages',
    changefreq: 'monthly',
    priority: '0.8',
  },
  {
    path: '/georgia',
    title: 'Travel to Georgia | Tour Packages | Zakher Travel',
    description: 'Georgia tours from Baku: Tbilisi, Kazbegi, wine regions and cultural journeys with Zakher Travel.',
    keywords: 'Georgia tours, Tbilisi travel, Caucasus tour packages',
    changefreq: 'monthly',
    priority: '0.8',
  },
  {
    path: '/kazakhstan',
    title: 'Travel to Kazakhstan | Tour Packages | Zakher Travel',
    description: 'Kazakhstan tour packages including Almaty and beyond. Professional guides, hotels and transfers by Zakher Travel.',
    keywords: 'Kazakhstan tours, Almaty travel, Central Asia tours',
    changefreq: 'monthly',
    priority: '0.75',
  },
  {
    path: '/kyrgyzstan',
    title: 'Travel to Kyrgyzstan | Tour Packages | Zakher Travel',
    description: 'Kyrgyzstan tours: Bishkek, Issyk-Kul and mountain adventures organized by Zakher Travel.',
    keywords: 'Kyrgyzstan tours, Bishkek travel, Central Asia tourism',
    changefreq: 'monthly',
    priority: '0.75',
  },
  {
    path: '/uzbekistan',
    title: 'Travel to Uzbekistan | Tour Packages | Zakher Travel',
    description: 'Uzbekistan tours: Samarkand, Bukhara, Tashkent and Silk Road experiences with Zakher Travel.',
    keywords: 'Uzbekistan tours, Silk Road travel, Samarkand tour',
    changefreq: 'monthly',
    priority: '0.75',
  },
  {
    path: '/poland',
    title: 'Travel to Poland | Tour Packages | Zakher Travel',
    description: 'Poland tour packages including Krakow and Warsaw. Cultural and city tours by Zakher Travel.',
    keywords: 'Poland tours, Krakow travel, Europe tour packages',
    changefreq: 'monthly',
    priority: '0.75',
  },
  {
    path: '/czech-republic',
    title: 'Travel to Czech Republic | Tour Packages | Zakher Travel',
    description: 'Czech Republic tours: Prague and beyond. European city breaks and group travel by Zakher Travel.',
    keywords: 'Czech Republic tours, Prague travel',
    changefreq: 'monthly',
    priority: '0.7',
  },
  {
    path: '/russia',
    title: 'Travel to Russia | Tour Packages | Zakher Travel',
    description: 'Russia tour packages and guided travel services organized by Zakher Travel.',
    keywords: 'Russia tours, Moscow travel packages',
    changefreq: 'monthly',
    priority: '0.7',
  },
  {
    path: '/ukraine',
    title: 'Travel to Ukraine | Tour Packages | Zakher Travel',
    description: 'Ukraine tour packages including Kyiv and cultural city tours by Zakher Travel.',
    keywords: 'Ukraine tours, Kyiv travel',
    changefreq: 'monthly',
    priority: '0.7',
  },
  {
    path: '/united-arab-emirates',
    title: 'Travel to UAE | Tour Packages | Zakher Travel',
    description: 'United Arab Emirates tour packages: Dubai, Abu Dhabi and luxury travel experiences by Zakher Travel.',
    keywords: 'UAE tours, Dubai travel packages, Abu Dhabi tours',
    changefreq: 'monthly',
    priority: '0.75',
  },
  tour(
    '/shahdag',
    'Gusar & Shahdag Tour',
    'Winter and summer tours to Gusar and Shahdag Mountain Resort in Azerbaijan. Ski, nature and adventure with Zakher Travel.',
    'Shahdag tour, Gusar travel, Azerbaijan mountain resort',
  ),
  tour(
    '/golf-azerbaijan',
    'Golf in Azerbaijan',
    'Golf tour packages in Azerbaijan with tee times, transfers and accommodation arranged by Zakher Travel.',
    'golf Azerbaijan, Baku golf tour, golf travel package',
  ),
  tour(
    '/special-golf-package-1',
    'Special Golf Package 1',
    'Premium golf travel package in Azerbaijan with Zakher Travel: courses, hotels and VIP transfers included.',
    'golf package Azerbaijan, luxury golf tour',
    '0.7',
  ),
  tour(
    '/special-golf-package-2',
    'Special Golf Package 2',
    'Exclusive golf itinerary in Azerbaijan tailored by Zakher Travel for groups and corporate travelers.',
    'golf tour Baku, corporate golf travel',
    '0.7',
  ),
  tour(
    '/absheron-tour',
    'Absheron Peninsula Tour',
    'Half-day and full-day Absheron tours: fire temple, burning mountain, oil history and Caspian coast with Zakher Travel.',
    'Absheron tour, Ateshgah Baku, Yanar Dag tour',
  ),
  tour(
    '/baku-night-tour',
    'Baku Night Tour',
    'Experience Baku by night: illuminated boulevard, Flame Towers and old city evening tour with Zakher Travel.',
    'Baku night tour, Baku evening excursion',
  ),
  tour(
    '/old-city-excursion',
    'Baku Old City Walking Tour',
    'Guided walking tour of Baku Old City (Icherisheher): Maiden Tower, Shirvanshah Palace and UNESCO heritage sites.',
    'Baku old city tour, Icherisheher walking tour, UNESCO Baku',
  ),
  tour(
    '/museum-gobustan-mud-volcano',
    'Gobustan Museum & Mud Volcanoes Tour',
    'Gobustan rock art museum and mud volcanoes day tour from Baku with professional guide and transport.',
    'Gobustan tour, mud volcanoes Azerbaijan, rock art Baku',
  ),
  tour(
    '/jeep-safari-tour-1',
    'Extreme Jeep Safari Tour 1',
    'Off-road jeep safari adventure in Azerbaijan with Zakher Travel  rugged terrain, nature and adrenaline.',
    'jeep safari Azerbaijan, off-road tour Baku',
  ),
  tour(
    '/jeep-safari-tour-2',
    'Extreme Jeep Safari Tour 2',
    'Advanced jeep safari expedition across Azerbaijan mountains and valleys with expert drivers and guides.',
    'extreme jeep tour, adventure travel Azerbaijan',
  ),
  tour(
    '/jeep-safari-on-the-gobustan-reserve-extreme',
    'Jeep Safari Gobustan Reserve + Extreme',
    'Combined Gobustan reserve jeep safari with extreme off-road sections, unique adventure tour from Baku.',
    'Gobustan jeep safari, extreme off-road Azerbaijan',
  ),
  tour(
    '/jeep-safari-on-the-gobustan-reserve',
    'Jeep Safari on Gobustan Reserve',
    'Scenic jeep safari through Gobustan reserve with prehistoric landscapes and guided commentary.',
    'Gobustan reserve tour, jeep tour Azerbaijan',
  ),
  tour(
    '/azerbaijani-cuisine',
    'Azerbaijani Cuisine Tour',
    'Taste Azerbaijan: food and culture tour featuring local restaurants, markets and traditional dishes.',
    'Azerbaijani food tour, Baku culinary tour, gastronomy Azerbaijan',
  ),
  tour(
    '/gabala-tour',
    'Gabala Tour',
    'Day trip to Gabala: Tufandag, Nohur Lake, ancient capital of Caucasian Albania. Full service tour from Baku.',
    'Gabala tour, Tufandag, day trip from Baku',
  ),
  tour(
    '/sheki-tour',
    'Sheki Tour',
    'Tour to Sheki Khan Palace, caravanserais and mountain scenery, cultural highlight of northwest Azerbaijan.',
    'Sheki tour, Khan Palace, Azerbaijan cultural tour',
  ),
  tour(
    '/khinalig-tour',
    'Khinalig Village Tour',
    'High-altitude tour to Khinalig village at 2200m: ancient Caucasus culture and breathtaking mountain views.',
    'Khinalig tour, mountain village Azerbaijan, remote tour Baku',
  ),
  tour(
    '/quba-tour',
    'Quba & Northern Forests Tour',
    'Northern Azerbaijan tour to Quba: forests, waterfalls, mountain air and traditional villages.',
    'Quba tour, northern Azerbaijan, forest tour Baku',
  ),
  tour(
    '/lahic-tour',
    'Lahij Artisan Village Tour',
    'Tour to Lahij: historic copper craftsmen village in the Caucasus mountains with guided cultural experience.',
    'Lahij tour, artisan village Azerbaijan, copper craftsmen',
  ),
  tour(
    '/poland-tours',
    'Poland Tours',
    'Multi-day Poland tour packages: Krakow, Warsaw and cultural highlights across Poland.',
    'Poland tours, Krakow Warsaw tour package',
  ),
  tour(
    '/krakow-tour',
    'Krakow Tour',
    'Krakow city tour: old town, Wawel Castle and Polish heritage with Zakher Travel.',
    'Krakow tour, Poland city break',
  ),
  tour(
    '/ukraine-tours',
    'Ukraine Tours',
    'Ukraine tour packages covering major cities and cultural landmarks.',
    'Ukraine tours, Eastern Europe travel',
  ),
  tour(
    '/kyiv-tour',
    'Kyiv Tour',
    'Kyiv city tour: golden-domed churches, history and culture of Ukraine capital.',
    'Kyiv tour, Kiev travel package',
  ),
  tour(
    '/kyrgyzstan-tours',
    'Kyrgyzstan Tours',
    'Kyrgyzstan tour packages: mountains, lakes and nomadic culture in Central Asia.',
    'Kyrgyzstan tours, Central Asia travel',
  ),
  tour(
    '/bishkek-tour',
    'Bishkek Tour',
    'Bishkek city and surroundings tour with local guides and comfortable transport.',
    'Bishkek tour, Kyrgyzstan city tour',
  ),
  tour(
    '/kazakhstan-tours',
    'Kazakhstan Tours',
    'Kazakhstan tour packages: Almaty, Astana and natural wonders of Central Asia.',
    'Kazakhstan tours, Central Asia packages',
  ),
  tour(
    '/almaty-tour',
    'Almaty Tour',
    'Almaty city tour: mountains, culture and modern Kazakhstan with Zakher Travel.',
    'Almaty tour, Kazakhstan city tour',
  ),
  tour(
    '/turkiye-tours',
    'Turkey Tours',
    'Turkey tour packages: Istanbul, Cappadocia, coastal resorts and custom itineraries.',
    'Turkey tours, Turkiye travel packages',
  ),
  tour(
    '/turkiye-tour',
    'Turkey Tour',
    'Individual Turkey tour with hotels, guides and transfers organized by Zakher Travel.',
    'Turkey tour, Turkiye holiday',
  ),
  tour(
    '/uzbekistan-tours',
    'Uzbekistan Tours',
    'Uzbekistan tour packages along the ancient Silk Road: Samarkand, Bukhara, Khiva.',
    'Uzbekistan tours, Silk Road packages',
  ),
  tour(
    '/uzbekistan-tour',
    'Uzbekistan Tour',
    'Custom Uzbekistan tour with expert guides, hotels and domestic transport.',
    'Uzbekistan tour, Central Asia holiday',
  ),
  tour(
    '/georgia-tours',
    'Georgia Tours',
    'Georgia tour packages: Tbilisi, Kazbegi, wine country and Caucasus adventures.',
    'Georgia tours, Tbilisi tour package',
  ),
  tour(
    '/georgia-tour',
    'Georgia Tour',
    'Tailored Georgia tour with professional guides and premium transport from Zakher Travel.',
    'Georgia tour, Caucasus travel',
  ),
  tour(
    '/russia-tours',
    'Russia Tours',
    'Russia tour packages for groups and individual travelers.',
    'Russia tours, Moscow St Petersburg travel',
  ),
  tour(
    '/russia-tour',
    'Russia Tour',
    'Individual Russia tour itinerary with Zakher Travel DMC services.',
    'Russia tour, guided travel Russia',
  ),
]

export const SEO_BY_PATH = Object.fromEntries(SEO_PAGES.map((page) => [page.path, page]))

export const SITEMAP_PAGES = SEO_PAGES.filter((page) => !page.noindex && !NOINDEX_PATHS.has(page.path))
